platform :ios, '8.0'
target 'XMPPFrameWorkDemo' do
use_frameworks!
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'JSONModel', '~> 1.2.0'
pod 'Masonry', '~> 0.6.4'
pod 'pop', '~> 1.0.9’
pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
end
